#!/bin/bash

# this script provides the following modificaitons:
#   move Settings and Notifications to the top of the list man page
#   hides the Tiles Overview
#   replaces the Mobile Overview with an enhanced version
#
# each of these modifications is optional and can be selected
#   at install time
#
# Note: both Enhanced Mobile Overview and hiding the Tile Overview modify main.qml
# so order of operations is important.
# The code also relies on a second request to backup an active file will not touch an existing backup

qmlDir=/opt/victronenergy/gui/qml
deviceListFile="$qmlDir/PageMain.qml"
mainPagesFile="$qmlDir/main.qml"
overviewMobileEnhancedFile="$qmlDir/OverviewMobileEnhanced.qml"
reasonMessageFile="$qmlDir/SystemReasonMessage.qml"
overviewAcValues="$qmlDir/OverviewAcValues.qml"
objectAcConnection="$qmlDir/ObjectAcConnection.qml"
overviewHub="$qmlDir/OverviewHub.qml"
overviewHubEnhanced="$qmlDir/OverviewHubEnhanced.qml"
overviewSolarCharger="$qmlDir/OverviewSolarCharger.qml"
tileTankFile="$qmlDir/TileTank.qml"
powerGaugeFile="$qmlDir/PowerGauge.qml"
powerGaugeBatteryFile="$qmlDir/PowerGaugeBattery.qml"
multiFile="$qmlDir/Multi.qml"
inverterPopupFile="$qmlDir/InverterModePopUp.qml"
acCurrentLimitPopUpFile="$qmlDir/AcCurrentLimitPopUp.qml"
tileTempFile="$qmlDir/TileTemp.qml"
hubDataFile="$qmlDir/HubData.qml"
marqueeFile="$qmlDir/Marquee.qml"
tileFile="$qmlDir/Tile.qml"

settingsDisplayFile="$qmlDir/PageSettingsDisplay.qml"
guiModsFile="$qmlDir/PageSettingsGuiMods.qml"
gaugesFile="$qmlDir/PageSettingsGuiModsGauges.qml"
versionsFile="$qmlDir/PageSettingsGuiModsVersions.qml"

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

#### end of lines to include SetupHelper

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    # display innitial message
    echo
    echo "This package modifies the GUI in several areas"
    echo "Refer to the ReadMe for an explaination of each modification"
    echo "Installation enables all modificaions by default"
    echo "  however each modificaiton can be enabled/disabled in the Settings Display menus"

    standardActionPrompt
fi

#### installing
if [ $scriptAction == 'INSTALL' ] ; then

    # create dbus Settings if they haven't been set previously
    # if one setting exists, assume they are all there
    # NOTE: if new settings are added in the future, change test for that one
    # to avoid creating that new parameter !!!!
    dbus-send --system --print-reply=literal --dest=com.victronenergy.settings /Settings/GuiMods/TimeFormat\
                com.victronenergy.BusItem.GetValue &> /dev/null
    if (( $? != 0 )); then
        logMessage "creating GuiMods Settings"
        dbus -y com.victronenergy.settings /Settings AddSettings\
            '%[{"path": "/GuiMods/GaugeLimits/PeakPower", "default":3000.0},\
            {"path":"/GuiMods/GaugeLimits/CautionPower", "default":2000.0},\
            {"path":"/GuiMods/GaugeLimits/ContiuousPower", "default":1000.0},\
            {"path":"/GuiMods/GaugeLimits/AcOutputMaxPower", "default":0.0},\
            {"path":"/GuiMods/GaugeLimits/PvChargerMaxPower", "default":0.0},\
            {"path":"/GuiMods/GaugeLimits/BatteryMaxDischargeCurrent", "default":100.0},\
            {"path":"/GuiMods/AcCurrentLimit/Preset1", "default":10},\
            {"path":"/GuiMods/AcCurrentLimit/Preset2", "default":20},\
            {"path":"/GuiMods/AcCurrentLimit/Preset3", "default":30},\
            {"path":"/GuiMods/AcCurrentLimit/Preset4", "default":50},\
            {"path":"/GuiMods/TemperatureScale", "default":1},\
            {"path":"/GuiMods/ShortenTankNames", "default":1},\
            {"path":"/GuiMods/UseEnhancedMobileOverview", "default":1},\
            {"path":"/GuiMods/UseEnhancedFlowOverview", "default":1},\
            {"path":"/GuiMods/ShowEnhancedFlowOverviewTanks", "default":1},\
            {"path":"/GuiMods/ShowEnhancedFlowOverviewTemps", "default":1},\
            {"path":"/GuiMods/ShowGauges", "default":1},\
            {"path":"/GuiMods/ShowTileOverview", "default":1},\
            {"path":"/GuiMods/MoveSettings", "default":1},\
            {"path":"/GuiMods/TimeFormat", "default":1} ]' > /dev/null
    fi

    # move setup options to Settings
    if [ -f "$setupOptionsDir/optionsSet" ]; then
        if [ -f "$setupOptionsDir/useEnhancedOverview" ] \
                || [ -f "$setupOptionsDir/moveSettings" ] \
                || [ -f "$setupOptionsDir/hideTileOverview" ] \
                || [ -f "$setupOptionsDir/enhancedFlow" ]; then
            logMessage "moving setup options to GuiMods Settings"
            
            if [ -f "$setupOptionsDir/useEnhancedOverview" ]; then
                setSetting 1 /Settings/GuiMods/UseEnhancedMobileOverview
            else
                setSetting 0 /Settings/GuiMods/UseEnhancedMobileOverview
            fi
            if [ -f "$setupOptionsDir/hideTileOverview" ]; then
                setSetting 1 /Settings/GuiMods/ShowTileOverview
            else
                setSetting 0 /Settings/GuiMods/ShowTileOverview
            fi
            if [ -f "$setupOptionsDir/enhancedFlow" ]; then
                dbus -y com.victronenergy.settings /Settings/GuiMods/UseEnhancedFlowOverview SetValue 1 &> /dev/null
                moveSetting "$setupOptionsDir/inverterPeakPower" /Settings/InverterLimits/PeakPower /Settings/GuiMods/GaugeLimits/PeakPower
                moveSetting "$setupOptionsDir/inverterCautionPower" /Settings/InverterLimits/PeakCautionPowerPower /Settings/GuiMods/GaugeLimits/CautionPower
                moveSetting "$setupOptionsDir/inverterContiuousPower" /Settings/InverterLimits/ContiuousPower /Settings/GuiMods/GaugeLimits/ContiuousPower
                moveSetting "$setupOptionsDir/systemPowerLimit" /Settings/InverterLimits/OutputPowerLimit /Settings/GuiMods/GaugeLimits/AcOutputMaxPower
                moveSetting "$setupOptionsDir/maxDischargeCurrent" /Settings/SystemSetup/MaxDischargeCurrent /Settings/GuiMods/GaugeLimits/BatteryMaxDischargeCurrent
                moveSetting "$setupOptionsDir/pvChargerMaxPower" /Settings/PvCharger/MaxPower /Settings/GuiMods/GaugeLimits/PvChargerMaxPower
                if [ -f "$setupOptionsDir/acCurrentLimitPresets" ]; then
                    read acCurrentLimitPreset1 acCurrentLimitPreset2 acCurrentLimitPreset3 acCurrentLimitPreset4 <<< $(cat "$setupOptionsDir/acCurrentLimitPresets")
                    setSetting acCurrentLimitPreset1 /Settings/GuiMods/AcCurrentLimit/Preset1
                    setSetting acCurrentLimitPreset2 /Settings/GuiMods/AcCurrentLimit/Preset2
                    setSetting acCurrentLimitPreset3 /Settings/GuiMods/AcCurrentLimit/Preset3
                    setSetting acCurrentLimitPreset4 /Settings/GuiMods/AcCurrentLimit/Preset4
                else 
                    moveSetting "" /Settings/InverterLimits/AcCurrentLimit/Preset1 /Settings/GuiMods/AcCurrentLimit/Preset1
                    moveSetting "" /Settings/InverterLimits/AcCurrentLimit/Preset1 /Settings/GuiMods/AcCurrentLimit/Preset2
                    moveSetting "" /Settings/InverterLimits/AcCurrentLimit/Preset1 /Settings/GuiMods/AcCurrentLimit/Preset3
                    moveSetting "" /Settings/InverterLimits/AcCurrentLimit/Preset1 /Settings/GuiMods/AcCurrentLimit/Preset4
                fi
            else
                dbus -y com.victronenergy.settings /Settings/GuiMods/UseEnhancedFlowOverview SetValue 0 > /dev/null
            fi
 
             # remove unused setup options (now in Settings)
            rm -f "$setupOptionsDir/useEnhancedOverview"
            rm -f "$setupOptionsDir/enhancedFlow"
            rm -f "$setupOptionsDir/hideTileOverview"
            rm -f "$setupOptionsDir/moveSettings"
            rm -f "$setupOptionsDir/acCurrentLimitPresets"
            rm -f "$setupOptionsDir/inverterCautionPower"
            rm -f "$setupOptionsDir/inverterContiuousPower"
            rm -f "$setupOptionsDir/inverterPeakPower"
            rm -f "$setupOptionsDir/maxDischargeCurrent"
            rm -f "$setupOptionsDir/pvChargerMaxPower"
            rm -f "$setupOptionsDir/shortenTankNames"
            rm -f "$setupOptionsDir/systemPowerLimit"
            rm -f "$setupOptionsDir/temperatureScale"
            rm -f "$setupOptionsDir/acCurrentLimitPresets"

             # remove old Settings
            dbus -y com.victronenergy.settings /Settings RemoveSettings\
                    '%["InverterLimits/PeakPower", "InverterLimits/ContiuousPower",\
                    "InverterLimits/CautionPower", "InverterLimits/OutputPowerLimit",\
                    "SystemSetup/MaxDischargeCurrent",\
                    "InverterLimits/AcCurrentLimit/Preset1", "InverterLimits/AcCurrentLimit/Preset2",\
                    "InverterLimits/AcCurrentLimit/Preset3", "InverterLimits/AcCurrentLimit/Preset4",\
                    "PvCharger/MaxPower" ]' > /dev/null

        fi
    fi
        
    logMessage "installing GuiMods files"
    updateActiveFile "$deviceListFile"
    updateActiveFile "$mainPagesFile"
    updateActiveFile "$overviewMobileEnhancedFile"
    updateActiveFile "$reasonMessageFile"
    updateActiveFile "$overviewAcValues"
    updateActiveFile "$objectAcConnection"
    updateActiveFile "$overviewHubEnhanced"
    updateActiveFile "$hubDataFile"
    updateActiveFile "$overviewSolarCharger"
    updateActiveFile "$powerGaugeFile"
    updateActiveFile "$powerGaugeBatteryFile"
    updateActiveFile "$multiFile"
    updateActiveFile "$inverterPopupFile"
    updateActiveFile "$acCurrentLimitPopUpFile"
    updateActiveFile "$tileTankFile"
    updateActiveFile "$tileTempFile"
    updateActiveFile "$settingsDisplayFile"
    updateActiveFile "$guiModsFile"
    updateActiveFile "$gaugesFile"
    updateActiveFile "$versionsFile"
    updateActiveFile "$marqueeFile"
    updateActiveFile "$tileFile"
    # clean up from previous versions
    restoreActiveFile "$overviewHub"
    
    logMessage "++ Package installed"
fi


# uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    restoreActiveFile "$deviceListFile"
    restoreActiveFile "$mainPagesFile"
    restoreActiveFile "$overviewMobileEnhancedFile"
    restoreActiveFile "$reasonMessageFile"
    restoreActiveFile "$overviewAcValues"
    restoreActiveFile "$objectAcConnection"
    restoreActiveFile "$overviewHubEnhanced"
    restoreActiveFile "$hubDataFile"
    restoreActiveFile "$overviewSolarCharger"
    restoreActiveFile "$tileTankFile"
    restoreActiveFile "$tileTempFile"
    restoreActiveFile "$powerGaugeFile"
    restoreActiveFile "$powerGaugeBatteryFile"
    restoreActiveFile "$multiFile"
    restoreActiveFile "$inverterPopupFile"
    restoreActiveFile "$acCurrentLimitPopUpFile"
    restoreActiveFile "$settingsDisplayFile"
    restoreActiveFile "$guiModsFile"
    restoreActiveFile "$gaugesFile"
    restoreActiveFile "$versionsFile"
    restoreActiveFile "$marqueeFile"
    restoreActiveFile "$tileFile"

    restoreActiveFile "$overviewHub"

    logMessage "++ Package uninstalled"
fi

if $filesUpdated ; then
    restartGui=true
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript
