#!/bin/bash

# this script provides the following modificaitons:
#   move Settings and Notifications to the top of the list man page
#   hides the Tiles Overview
#   replaces the Mobile Overview with an enhanced version
#
# each of these modifications is optional and can be selected
#   at install time
#
# Note: both Enhanced Mobile Overview and hiding the Tile Overview modify main.qml
# so order of operations is important.
# The code also relies on a second request to backup an active file will not touch an existing backup

qmlDir=/opt/victronenergy/gui/qml
deviceListFile="$qmlDir/PageMain.qml"
mainPagesFile="$qmlDir/main.qml"
overviewMobileEnhancedFile="$qmlDir/OverviewMobileEnhanced.qml"
reasonMessageFile="$qmlDir/SystemReasonMessage.qml"
overviewAcValues="$qmlDir/OverviewAcValues.qml"
objectAcConnection="$qmlDir/ObjectAcConnection.qml"
overviewHub="$qmlDir/OverviewHub.qml"
overviewSolarCharger="$qmlDir/OverviewSolarCharger.qml"
tileTankFile="$qmlDir/TileTank.qml"

installEnhancedTank=false

# log file for this package
# if not a null string, options to display the log file are presented
packageLogFile="/var/log/gui/current"

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

if [ $scriptAction == 'EXIT' ] ; then
    exit
fi

checkFileSets

#### end of lines to include SetupHelper

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    # display innitial message
    echo
    echo "This package modifies the GUI in several areas"
    echo "All modificaitons are explained below with a choice to install each one individually"

    standardActionPrompt enableReinstall
    
    # prompt for remaining parameters needed for activation
    if [ $scriptAction == 'PROMPT' ]; then
        echo
        echo "The Enhanced overview includes the following changes:"
        echo "  1) Tiles are arranged to more cloesly follow the power flow through the system"
        echo "  2) Voltage, current and frequency values are added to the AC in and out tiles"
        echo "  3) Battery remaining time is added to the Battery tile"
        echo "  4) ESS reason codes are replaced with a text version to make them more meaningful"
        echo "  5) ESS reason text and other notifications are combined into a single "marquee" line"
        echo "  6) The pump switch is hidden unless the Venus relay is configured for pump control"
        echo "  7) AC Mode switch includes INVERTER ONLY mode"
        echo
        echo "Tank enhancements are also included:"
        echo "  1) Bar text turns red and indicates NO RESPONSE for sensor connection errors"
        echo "  2) Color of bar turns red on limits instead of blinking"
        echo "  3) Color of bar text turns red when bar lenght is too short to be seen"
        echo "  4) If space is limited, bar graph height and associated text are reduced"
        echo "  5) Added custom tank name"
        echo "  6) Added absolute quantity (e.g., gallons) next to %"
        echo "  7) List scrolls if all tanks don't fit"
        echo        
        yesNoPrompt "Do you wish to install the Enhanced Mobile Overview Page? (y/n): "
        if $yesResponse ; then
            touch $scriptDir/useEnhancedOverview
       else
            rm -f $scriptDir/useEnhancedOverview
        fi
        echo
        yesNoPrompt "Do you wish to move Settings and Notifications to the top of the Device List? (y/n): "
        if $yesResponse ; then
            touch $scriptDir/moveSettings
       else
            rm -f $scriptDir/moveSettings
        fi
        echo
        yesNoPrompt "Do you wish to hide the Tile Overview? (y/n): "
        if $yesResponse ; then
            touch $scriptDir/hideTileOverview
       else
            rm -f $scriptDir/hideTileOverview
        fi
        echo
        echo "The Enhanced flow includes the following changes:"
        echo "  1) Voltage, current and frequency are shown for AC in and out"
        echo "  2) Current is shown for DC Loads"
        echo "  3) Tanks are shown along the bottom of the page"
        echo "      List scrolls horizontally if necessary"
        echo "  4) Other Tank enhancements listed above are also included"
        echo "  5) PV Charger tile shows voltage and current"
        echo "  6) Time is displayed in inverter icon"
        echo        
        yesNoPrompt "Do you wish install flow Overview enhancements? (y/n): "
        if $yesResponse ; then
            touch $scriptDir/enhancedFlow
       else
            rm -f $scriptDir/enhancedFlow
        fi
        scriptAction='INSTALL'
    fi
fi

#### installing
if [ $scriptAction == 'INSTALL' ] ; then
    if [ -f "$scriptDir/moveSettings" ]; then
        logMessage "Moving Settings & Notifications to top of Device List"
        updateActiveFile "$deviceListFile"
    else
        restoreActiveFile "$deviceListFile"
    fi
    if [ -f "$scriptDir/hideTileOverview" ]; then
        logMessage "Hiding the Tile Overview"
        updateActiveFile "$mainPagesFile"
    else
        restoreActiveFile "$mainPagesFile"
    fi
    if [ -f "$scriptDir/useEnhancedOverview" ] ; then
        logMessage "installing Enhanced Mobile Overview"
        updateActiveFile "$overviewMobileEnhancedFile"
        logMessage "installing System Reason Message"
        updateActiveFile "$reasonMessageFile"
        installEnhancedTank=true

        # modify main.qml to show enhanced mobile overview
        if [ $(grep -c OverviewMobileEnhanced.qml "$mainPagesFile") == 0 ]; then
            backupActiveFile "$mainPagesFile"
            sed -i -e 's/OverviewMobile.qml/OverviewMobileEnhanced.qml/' "$mainPagesFile"
            filesUpdated=true
        fi
    else
        restoreActiveFile "$overviewMobileEnhancedFile"
        restoreActiveFile "$reasonMessageFile"
        if [ $(grep -c OverviewMobileEnhanced.qml "$mainPagesFile") != 0 ]; then
            sed -i -e 's/OverviewMobileEnhanced.qml/OverviewMobile.qml/' "$mainPagesFile"
            filesUpdated=true
        fi
    fi
    if [ -f "$scriptDir/enhancedFlow" ]; then
        logMessage "installing enhanced Flow overview"
        updateActiveFile "$overviewAcValues"
        updateActiveFile "$objectAcConnection"
        updateActiveFile "$overviewHub"
        updateActiveFile "$overviewSolarCharger"
        installEnhancedTank=true
    else
        restoreActiveFile "$overviewAcValues"
        restoreActiveFile "$objectAcConnection"
        restoreActiveFile "$overviewHub"
        restoreActiveFile "$overviewSolarCharger"
    fi
    if $installEnhancedTank ; then
        logMessage "installing enhanced Tank tile"
        updateActiveFile "$tileTankFile"
    # restore tank file in case install was run again manually
    else
        restoreActiveFile "$tileTankFile"
    fi
    logMessage "++ Package installed"
fi

# uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    restoreActiveFile "$deviceListFile"
    restoreActiveFile "$mainPagesFile"
    restoreActiveFile "$overviewMobileEnhancedFile"
    restoreActiveFile "$reasonMessageFile"
    restoreActiveFile "$overviewAcValues"
    restoreActiveFile "$objectAcConnection"
    restoreActiveFile "$overviewHub"
    restoreActiveFile "$overviewSolarCharger"
    restoreActiveFile "$tileTankFile"
    logMessage "++ Package uninstalled"
fi

if $filesUpdated ; then
    restartGui=true
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript
