#!/bin/sh

# this script selects the correct location for helper Resources
#	and sources them into the setup script
#
# for backward compatibility, CommonResources in the SetupHelper directory
#	links to this file, not CommonResources
#	CommonResources previously sourced the other files
#	now sourcing all resource files is done from here
#
# the helper files location is either the package directory or in the SetupHelper directory
# if both are present, the one with the newer version number is incorporated
#	into the setup script
#
# this script should be sourced in the setup script before any other activities

#	NOTE: this script uses VersionResources ONLY
#	it does source any other helper files since final location has not yet been chosen

pkgDir=$( dirname $0 )
pkgName=$( basename $pkgDir )
shDir=$( dirname "$pkgDir" )/SetupHelper

# assume helper files are in package directory - change below if not
helperFilesDir="$pkgDir/HelperFiles"

if [ -e "$helperFilesDir" ]; then
	# both helper file sets present - compare them and choose the newest
	if [ -e "$pkgDir/HelperFiles/version" ] && [ -e "$shDir/HelperFiles" ]; then
		# temporarily source the local VersionResources
		source "$pkgDir/HelperFiles/VersionResources"
		versionResourcesSourced="no" # make sure the correct VersionResources will be included later
		# setup helper files are newer - switch to those helper files
		compareVersions $( cat "$shDir/version" ) $( cat "$pkgDir/HelperFiles/version" )
		if (( $? == 1 )); then
			helperFilesDir="$shDir/HelperFiles"
		fi
	fi
elif [ -e "$shDir/HelperFiles" ]; then
	echo "#### sh helpers"
	helperFilesDir="$shDir/HelperFiles"
else
	echo "$pkgName: helper files not found - can't continue" | tee -a "/data/log/SetupHelper"
	exit 1
fi

# if we get here, helper files were located - source the files
helperFileList=(EssentialResources LogHandler VersionResources CommonResources \
					DbusSettingsResources ServiceResources)
for file in ${helperFileList[@]}; do
	if [ -f "$helperFilesDir/$file" ]; then
		echo source "$helperFilesDir/$file"
	else
		echo "$pkgName: helper file $file not found - can't continue" | tee -a "/data/log/SetupHelper"
		exit 1
	fi
done

exit
